// loading constants
export const DISPLAY_LOADING = "DISPLAY_LOADING";
export const HIDE_LOADING = "HIDE_LOADING";

// login constants
export const USER_SIGNIN_API = "USER_SIGNIN_API";
export const USER_LOGIN = "USER_LOGIN";

// Project constants
export const GET_PROJECT_CATEGORY_API = "GET_PROJECT_CATEGORY_API";
export const SET_PROJECT_CATEGORY = "SET_PROJECT_CATEGORY";

export const CREATE_PROJECT_API = "CREATE_PROJECT_API";
export const GET_PROJECT_LIST_API = "GET_PROJECT_LIST_API";
export const SET_PROJECT_LIST = "SET_PROJECT_LIST";

// Drawer constants
export const OPEN_DRAWER = "OPEN_DRAWER";
export const CLOSE_DRAWER = "CLOSE_DRAWER";
export const OPEN_FORM_EDIT_PROJECT = "OPEN_FORM_EDIT_PROJECT";
export const SET_SUBMIT_EDIT_PROJECT_FUNC = "SET_SUBMIT_EDIT_PROJECT_FUNC";
