// loading constants
export const DISPLAY_LOADING = "DISPLAY_LOADING";
export const HIDE_LOADING = "HIDE_LOADING";

// User constants
export const USER_SIGNIN_API = "USER_SIGNIN_API";
export const USER_LOGIN = "USER_LOGIN";

export const GET_USER_SEARCH_API = "GET_USER_SEARCH_API";
export const SET_USER_SEARCH = "SET_USER_SEARCH";

export const GET_USER_BY_PROJECT_ID_API = "GET_USER_BY_PROJECT_ID_API";
export const SET_USER_BY_PROJECT_ID = "SET_USER_BY_PROJECT_ID";

// Drawer constants
export const OPEN_DRAWER = "OPEN_DRAWER";
export const CLOSE_DRAWER = "CLOSE_DRAWER";

// Form constants
export const OPEN_FORM_EDIT_PROJECT = "OPEN_FORM_EDIT_PROJECT";
export const OPEN_FORM_CREATE_TASK = "OPEN_FORM_CREATE_TASK";

// Project constants
export const GET_PROJECT_CATEGORY_API = "GET_PROJECT_CATEGORY_API";
export const SET_PROJECT_CATEGORY = "SET_PROJECT_CATEGORY";

export const CREATE_PROJECT_API = "CREATE_PROJECT_API";
export const GET_PROJECT_LIST_API = "GET_PROJECT_LIST_API";
export const SET_PROJECT_LIST = "SET_PROJECT_LIST";

export const SET_SUBMIT_FUNCTION = "SET_SUBMIT_FUNCTION";

export const SET_PROJECT_EDIT = "SET_PROJECT_EDIT";
export const UPDATE_PROJECT_API = "UPDATE_PROJECT_API";
export const DELETE_PROJECT_API = "DELETE_PROJECT_API";

export const GET_PROJECT_DETAIL_API = "GET_PROJECT_DETAIL_API";
export const SET_PROJECT_DETAIL = "SET_PROJECT_DETAIL";

// User Project constants
export const ASSIGN_USER_PROJECT_API = "ASSIGN_USER_PROJECT_API";
export const REMOVE_USER_PROJECT_API = "REMOVE_USER_PROJECT_API";

// Notification constants
export const SHOW_NOTIFICATION = "SHOW_NOTIFICATION";

// Task constants
export const GET_TASK_TYPE_API = "GET_TASK_TYPE_API";
export const SET_TASK_TYPE_LIST = "SET_TASK_TYPE_LIST";

export const GET_TASK_PRIORITY_API = "GET_TASK_PRIORITY_API";
export const SET_TASK_PRIORITY_LIST = "SET_TASK_PRIORITY_LIST";

export const GET_TASK_STATUS_API = "GET_TASK_STATUS_API";
export const SET_TASK_STATUS_LIST = "SET_TASK_STATUS_LIST";

export const CREATE_TASK_API = "CREATE_TASK_API";

export const SET_TASK_DETAIL_MODAL = "SET_TASK_DETAIL_MODAL";
export const GET_TASK_DETAIL_MODAL_API = "GET_TASK_DETAIL_MODAL_API";
export const UPDATE_TASK_DETAIL_MODAL = "UPDATE_TASK_DETAIL_MODAL";
export const UPDATE_TASK_ASSIGNESS = "UPDATE_TASK_ASSIGNESS";
export const REMOVE_TASK_ASSIGNEE = "REMOVE_TASK_ASSIGNEE";

export const UPDATE_TASK_API = "UPDATE_TASK_API";
export const HANDLE_CHANGE_SAGA = "HANDLE_CHANGE_SAGA";
